### ISSUE TITLE
love the sunburst!  ... but how to config with Vue

### ISSUE THREAD

**Issue by timelyportfolio** [d2bjs/d2b#1]
Thanks so much for this fantastic library with documentation and even `vue` integration.  I love sunburst, but I am having trouble with sunburst `config` to use `name` instead of `label`.  I have this working without `vue`, but I have not yet found the secret combination.  I am determined to figure it out, but I thought perhaps you could give me a clue.  I assume the answer will be something like the `vue` [pie chart example](https://github.com/d2bjs/d2b/blob/master/examples/chart/pie/pie-vue.html).

```
        pieChartConfig: function (chart) {
          chart.donutRatio(0.5);
        }
```

Thanks again for all the effort and diligence and open source!

**Comment by timelyportfolio** [comment]
Ok, making progress.  I was able to configure everything except `color` with

```
sunburstChartConfig: function(chart) {
  chart.sunburst = chart.sunburst()
    .size(function(d){return d.x})
    .key(function(d){return d.name})
    .label(function(d){return d.name}) 
}
```

With the above `config`, color works for the `breadcrumbs`, but not for the sunburst.  How do I get access to the `color` scale with `chart.color(function(d){return color(d.name)})`?

![image](https://cloud.githubusercontent.com/assets/837910/25234762/afa7c734-25a8-11e7-9d53-eb5dbff91d33.png)

**Comment by kevinwarne** [comment]
Hey! I initially didn't see the need for a label accessor on the sunburst chart as this was achievable by going indirectly through the **svgSunburst** generator. However looking at how the colors and keys were somewhat dependent on this I decided to add it. So now you should be able to do the following with the latest d2b version pushed minutes ago.

```javascript
var sunburst = d2b.chartSunburst().label(function (d) { return d.name; });
```

**Comment by kevinwarne** [comment]
So with vue, you should be able to do:

```javascript
sunburstChartConfig: function(chart) {
  chart.label(function (d) { return d.name; })
  chart.sunburst().size(function (d) { return d.x; });
}
```

This also will now propagate the label accessor to the key and color accessors. So you shouldn't need to redefine those unless there is a different reason for doing this.

Modified the above snippet to include the size accessor as you did which still needs to be done indirectly through the **svgSunburst** generator.

**Comment by timelyportfolio** [comment]
Wow, thanks so much for the very quick response!  Now, I can use `d2b` with a unofficially "standard" `d3` hierarchy.   As I was playing, I veered from the "standard" and named size `x`.  For anyone who might want find themselves in the non-standard `size` scenario, I will paste below.

```
sunburstChartConfig: function(chart) {
  chart.label(function(d){return d.name});
  chart.sunburst.size(function(d){return d.x});
}
```

Thanks again!

**Comment by timelyportfolio** [comment]
For a little more information on my use case, I am primarily a `R` developer.  `R` has a thing called [`htmlwidgets`](https://htmlwidgets.org) which provides a framework for combining R with `HTML/JS/CSS`.  In general, `htmlwidgets` would use the non-framework `d2b.chartSunburst`, as in the [`sunburstR`](https://github.com/timelyportfolio/sunburstR) (authored by me based on Kerry Rodden's gist).  However, I am also attempting to ease integration of `vuejs` with `R` with the package [`vueR`](https://github.com/timelyportfolio/vueR), so I wanted to try both methods of integration.

I will post an example of R + `d2b` by the end of the day.  I hope it brings a little more attention to your very fine library!

Thanks again.

**Comment by kevinwarne** [comment]
This is excellent work! I will definitely be checking out R's htmlwidgets and your web integrations. Kerry Rodden's sunburst gist was actually one of my inspirations for the d2b sunburst UI. The d2b vue components are very simple wrappers that could probably be applied to many d3 generators. I'm hoping to add more features and hooks to the d2b vue integrations in the future as my work has recently adopted Vue.js into our web development stack.

Another uncommon chart type that might be useful in R is the d2b.axisChart **bubblePack** generator. I haven't put together an example on the d2b website yet, but you can see an older version in action at [new-mexico-workforce](http://workforce.unm.edu/) under the "Employment Rate vs Salary" chart. Each of the symbols here are expandable adding another layer of data exploration.

Thanks for taking an interest in d2b!

**Comment by timelyportfolio** [comment]
Just discovered that my `config` for `x` instead of `size` fails on resize or any update/re-render.  I will try to find a solution.

`bubblePack` is very interesting.  Will see if I can figure out a good use for it.

**Comment by kevinwarne** [comment]
I think it's probably because the chart's sunburst property is getting overwritten:

```
  chart.sunburst = chart.sunburst()
    .size(function(d){return d.x});
```
try just
```
chart.sunburst().size(function(d){return d.x});
```

**Comment by timelyportfolio** [comment]
Thanks, I tried that originally, but abandoned because I thought that was the source of my earlier error.  This definitely works and is a far better approach.  Thanks!  I corrected my above comment `config`.
