### ISSUE TITLE
add format prop for sunburst

### ISSUE THREAD

**Issue by timelyportfolio** [d2bjs/d2b#14]
Finally circling back to add your amazing sunburst to the R package `sunburstR`.  What are your thoughts on a `format` (see [line](https://github.com/d2bjs/d2b/blob/master/src/scripts/chart/sunburst.js#L52)) prop for the sunburst legend and tooltip in case a user is not working with whole numbers?  I'm happy to help if you deem valuable and appropriate.

Thanks so much!

**Comment by kevinwarne** [comment]
Hello again, glad to have you back working on this. There are accessor hooks to customize the built in tooltip and breadcrumb html. Here is a fiddle to see it working in action: https://jsfiddle.net/ujjurd9c/16/

Of course in this example we lose the styling a bit. To fix that you would need to use your own html template for these breadcrumbs / tooltips. Or you can just use the same format I'm using behind the scenes in d2b, something like:

```html
<div class = 'd2b-sunburst-label'>
  *label here*
</div>
<div class = 'd2b-sunburst-value'>
  *value here*
  <div class = 'd2b-sunburst-percent'>
    *percent here*
  </div>
</div>
```
Let me know if you think this might work. Thanks!

**Comment by timelyportfolio** [comment]
@kevinwarne, thanks so much, this is great.  I think I can use this to add some customizability in the widget implementation.

**Comment by kevinwarne** [comment]
Sounds like a good customization to have. Let me know if you have more questions. Also, since we spoke a while back the Vue d2b components have been moved into a separate plugin called “vue-d2b” just a heads up in case you are hoping to still use those.
