### ISSUE TITLE
Sunburst colors. 

### ISSUE THREAD

**Issue by Dekermanjian** [d2bjs/d2b#15]
Hi I am trying to create a sunburst graph for my data and I would like each variable to have a specific color. However I can't seem to get it to work properly as some variables get colored but the majority of them are the same color. I am following this example https://bl.ocks.org/timelyportfolio/be8412a07b00de20e725e3757605c63f/fb1c90563631c6901c1280dec883fb13e6e3577a
But in the treemap creation I have specified type = 'categorical' and have a column of all the unique variables set as vColor. 
Any help would be greatly appreciated.

**Comment by kevinwarne** [comment]
Hey, in case you are still working on this, here are a few ways to set custom colors on the d2b sunburst arcs. There are others, but these will hopefully be enough to get you started. 

```javascript
// FIRST: initialize a new sunburst

// vanilla JS
var sunburst = d2b.chartSunburst()

// OR ES6 imports
import { chartSunburst } from 'd2b'
const sunburst = chartSunburst()

// OR the vue-d2b plugin pass the :config prop a callback function, possibly defined in the instance data
data() {
      config(sunburst) {
            // Then configure the sunburst here..
      }
}


// SECOND: configure the sunburst color property using one of these methods
 
/* force the entire chart to use a specific color */
sunburst.color('red')

/* use a built in d3 color scale to color by the arc data label */
var colorScale = d3.scaleOrdinal(d3.schemeDark2)
sunburst.color(function (d) {
	return colorScale(d.label) 
})

/* define the color directly on the arc data and reference it. This method would require
    you to set a `color` attribute on each data arc. like: {label: 'arc label', color: 'purple', size: 15} */
sunburst.color(function (d) {
	return d.color
})
```

If you are using vue-d2b this can be done in the config prop callback. Hopefully this helps. Let me know if you have more questions.

Here is a fiddle example if you want to see these in action. Cheers! https://jsfiddle.net/tc94zb5d/9/

**Comment by Dekermanjian** [comment]
Hey Kevin,
thank you for the reply and help. What I wanted to do was color each unique variable a unique color. I ended up using var color = d3.scale.category20(); from "http://d3js.org/d3.v3.min.js” and it worked nicely. But it only has 20 colors and I have more variables, so now I am going to try to define my own colors using

d3.scale.category20 = function() {
    return d3.scale.ordinal().range(d3_category20);
};
var d3_category20 = [
  0x1f77b4, 0xaec7e8,
  0xff7f0e, 0xffbb78,
  0x2ca02c, 0x98df8a,
  0xd62728, 0xff9896,
  0x9467bd, 0xc5b0d5,
  0x8c564b, 0xc49c94,
  0xe377c2, 0xf7b6d2,
  0x7f7f7f, 0xc7c7c7,
  0xbcbd22, 0xdbdb8d,
  0x17becf, 0x9edae5
].map(d3_rgbString);

Again, thank you for the reply, I really appreciate it.


On Jun 15, 2018, at 12:19 PM, Kevin Warne <notifications@github.com<mailto:notifications@github.com>> wrote:


Hey, in case you are still working on this, here are ways to set custom colors on the d2b sunburst arcs.

/* force the entire chart to use a specific color */
sunburst.color('red')

/* use a built in d3 color scale to color by the arc data label */
var colorScale = d3.scaleOrdinal(d3.schemeDark2)
sunburst.color(function (d) {
        return colorScale(d.label)
})

/* define the color directly on the arc data and reference it. This method would require
    you to set a `color` attribute on each data arc. like: {label: 'arc label', color: 'purple', size: 15} */
sunburst.color(function (d) {
        return d.color
})

If you are using vue-d2b this can be done in the config prop callback. Hopefully this helps. Let me know if you have more questions.

Here is a fiddle example if you want to see these in action. Cheers! https://jsfiddle.net/tc94zb5d/9/

**Comment by kevinwarne** [comment]
Sounds like your solution is working. I would recommend switching to using a d3 version 4 color scale rather than version 3. See: https://github.com/d3/d3-scale-chromatic Otherwise that looks like a great solution.
