### ISSUE TITLE
Zoomable sunburst ring sizes in zoomed form are visually misleading. 

### ISSUE THREAD

**Issue by Dekermanjian** [d2bjs/d2b#16]
Hi, I am using vue d2b to generate zoomable sunburst plots. I have come across an issue where when you zoom in and make a particular ring the new 'root' the slices that follow may visually be misleading. For example the slice may indicate 30% of the root but visually it would ring around more that halfway around the circle. 

This can be seen here https://bl.ocks.org/timelyportfolio/be8412a07b00de20e725e3757605c63f/fb1c90563631c6901c1280dec883fb13e6e3577a 

If you zoom in on b.2, b.2.c is 29% but rings around more than halfway around the circle. 

Is there a fix for this?

**Comment by kevinwarne** [comment]
There is definitely something odd going on with the computations in that sunburst example. The sunburst zooming should work how you describe it (the percentages visually corresponding to the arc sizes). I'll find some time this week to debug this issue and let you know when it is fixed. Thank you for pointing it out.

**Comment by Dekermanjian** [comment]
Thank you very much. That would be extremely helpful.

On Jun 18, 2018, at 9:17 AM, Kevin Warne <notifications@github.com<mailto:notifications@github.com>> wrote:


There is definitely something odd going on with the computations in that sunburst example. The sunburst zooming should work how you describe it (the percentages visually corresponding to the arc sizes). I'll find some time this week to debug this issue and let you know when it is fixed. Thank you for pointing it out.

**Comment by Dekermanjian** [comment]
I also wanted to note, that using the treemap() function before d3_nest() causes an inflation in the counts. I tried generating the graph without using treemap(), the counts are fixed but the original issue still persists. Also without the treemap() I can no longer sort the data by size to generate a sunburst with decreasing arcs. If I sort I only get decreasing arcs in the first inner arc but not the outer ones. Is there a way to sort the size within javascript? I am not at all adept in javascript, any help would be appreciated. 

I have tried:
computed: {
  sortedArray: function() {
    function compare(a, b) {
      if (a.size < b.size)
        return -1;
      if (a.size > b.size)
        return 1;
      return 0;
    }

    return this.arrays.sort(compare);
  }
}

but the arcs within the graph did not change.

**Comment by kevinwarne** [comment]
Started to look into this. It seems like the original issue you described occurs when explicitly providing parent node sizes. For example:

```
{
  name: 'parent',
  size: 5,
  children: [
    {name: 'child 1', size: 2},
    {name: 'child 2', size: 3},
  ]
}
```

In this example the parent object has a size. But that is redundant because the leaf child object sizes will aggregate automatically through d2b. If we remove the redundant sizes like: 

```
{
  name: 'parent',
  children: [
    {name: 'child 1', size: 2},
    {name: 'child 2', size: 3},
  ]
}
```

the zooming will function properly. The reason I allowed explicit parent node sizing is because there are certain use cases where this is still important. I will continue to look into the bug and hopefully come up with a clean resolution.

**Comment by Dekermanjian** [comment]
I see, does that mean that when I nest my data.frame with d3_nest() I should not include the value_cols parameter? would I have to also change where I call d.size like here:
.sunburst().size(function(d){return d.size });  ?

On Jun 21, 2018, at 3:01 PM, Kevin Warne <notifications@github.com<mailto:notifications@github.com>> wrote:


Started to look into this. It seems like the original issue you described occurs when explicitly providing parent node sizes. For example:

{
  name: 'parent',
  size: 5,
  children: [
    {name: 'child 1', size: 2},
    {name: 'child 2', size: 3},
  ]
}


In this example the parent object has a size. But that is redundant because the leaf child object size will aggregate automatically through d2b. If we remove the redundant sizes like:

{
  name: 'parent',
  children: [
    {name: 'child 1', size: 2},
    {name: 'child 2', size: 3},
  ]
}


the zooming will function properly. The reason I allowed explicit parent node sizing is because there are certain use cases where this is still important. I will continue to look into the bug and hopefully come up with a clean resolution.

**Comment by kevinwarne** [comment]
I made a change to d2b to only read in leaf node values. After a bit more deliberation I decided this was the desired functionality of the sunburst. This should solve your problem in all cases described above. But let me know if the issue persists. The fix should be on `d2b version 0.5.2` or if you are using vue, `vue-d2b version 1.0.12`. Thanks!

**Comment by Dekermanjian** [comment]
Kevin, I gave it a run and the visualization is working properly however my counts are now incorrect. I have a cohort number of 28 and while it was correctly counted as 28 earlier now it says it is only 14. Do I need to stop grouping and counting similar sequences before nesting into JSON with d3_nest?

On Jun 24, 2018, at 2:55 PM, Kevin Warne <notifications@github.com<mailto:notifications@github.com>> wrote:


I made a change to d2b to only read in leaf node values. After a bit more deliberation I decided this was the desired functionality of the sunburst. This should solve your problem in all cases described above. But let me know if the issue persists. The fix should be on d2b version 0.5.2 or if you are using vue, vue-d2b version 1.0.12. Thanks!

**Comment by kevinwarne** [comment]
So usually a sunburst hierarchy is comprised of parent -> child node associations where all arc sizes are derived from the leaf nodes. For example: 

```
{
  "name": "a",
  "children": [
    {
      "name": "a.1",
      "size": 1
    },
    {
      "name": "a.2",
      "size": 3
    },
  ]
}
```

Would be the same sunburst as this one: 

```
{
  "name": "a",
  "size": 4,
  "children": [
    {
      "name": "a.1",
      "size": 1
    },
    {
      "name": "a.2",
      "size": 3
    },
  ]
}
```

e.g. the sizes are **not** cumulative up the tree, if they were this would result in the size of node "a" being 8 and then "a.1" and "a.2" would not properly distribute the size of their parent.

Although I may be way off base on this. Can you give me a sample example for what you are trying to achieve? Thanks 😄

**Comment by Dekermanjian** [comment]
I am working on treatment pathways, where I track the progression of treatments patients have, and how many patients have a particular sequence of treatments. And now the number of patients that was the number of the root is no longer correct as well as the rest of the counts.

On Jun 24, 2018, at 3:49 PM, Kevin Warne <notifications@github.com<mailto:notifications@github.com>> wrote:


So usually a sunburst hierarchy is comprised of parent -> child node associations where all arc sizes are derived from the leaf nodes. For example:

{
  "name": "a",
  "children": [
    {
      "name": "a.1",
      "size": 1
    },
    {
      "name": "a.2",
      "size": 3
    },
  ]
}


Would be the same sunburst as this one:

{
  "name": "a",
  "size": 4,
  "children": [
    {
      "name": "a.1",
      "size": 1
    },
    {
      "name": "a.2",
      "size": 3
    },
  ]
}


e.g. the sizes are not cumulative up the tree, if they were this would result in the size of node "a" being 8 and then "a.1" and "a.2" would not properly distribute the size.

Although I may be way off base on this. Can you give me a sample example for what you are trying to achieve? Thanks 😄

**Comment by kevinwarne** [comment]
Alright. Let me think on this a bit more and see if I can implement a couple properties to give full customization over the sizes and percentages.

**Comment by Dekermanjian** [comment]
Kevin, I still don’t fully understand why the total count would be incorrect with the changes you’ve made?

On Jun 24, 2018, at 4:00 PM, Kevin Warne <notifications@github.com<mailto:notifications@github.com>> wrote:


Alright. Let me think on this a bit more and see if I can implement a couple properties to give full customization over the sizes and percentages.

**Comment by Dekermanjian** [comment]
Kevin, if it would be helpful, I could send you my data frame, the sunburst with the correct counts and the current sunburst with the incorrect counts. My emai ad. is jonathan.dekermanjian@ucdenver.edu

**Comment by kevinwarne** [comment]
This has been resolved with the addition of an optional "size" attribute that can be added to parent (non-leaf) nodes  in the sunburst data. This allows for oversizing a node to be larger than it's relative leaf nodes account for.
