### ISSUE TITLE
Inner labels in pieChart

### ISSUE THREAD

**Issue by maximus1010101** [d2bjs/d2b#18]
Hello,
Thanks for your work!

How I can replace inner labels in pieChart's arcs? I want use the labels from data obj instead the procents.

**Comment by kevinwarne** [comment]
Hmm, I don't think I implemented that feature yet. Let me work on it this weekend and see if I can come up with a solution.

**Comment by kevinwarne** [comment]
Added support in d2b `v0.5.5`.

Here is a solution to customizing the inner pie chart labels https://jsfiddle.net/7Lhcuy4x/2/.

It shows a custom accessor method `arcLabel` to override the default percents. This method accepts the arc datum `d`.

In the future I would like to extend [d3-annotation](http://d3-annotation.susielu.com/) to the d2b pie chart. But that may require some more intensive refactoring.

**Comment by kevinwarne** [comment]
Oops, I provided the wrong fiddle initially. I updated it, sorry about that.
