### ISSUE TITLE
Using a band scale with barchart, triggers tooltips in the wrong position.

### ISSUE THREAD

**Issue by jondavidjohn** [d2bjs/d2b#20]
You can see in the official example that the tooltip pops up before the cursor hits the bar (left to right) and disappears before the cursor clears the bar.  Looks like this may be a misalignment?

http://www.d2bjs.org/example_categories/1/entries/6

![bartooltip](https://user-images.githubusercontent.com/401520/45269429-d3976600-b453-11e8-9012-2a0342038d2e.gif)

**Comment by kevinwarne** [comment]
This might be a browser inconsistency. I’m not experiencing it. What browser are you using?

**Comment by jondavidjohn** [comment]
Yeah, looks like a firefox issue 😕

**Comment by kevinwarne** [comment]
Still planning to circle back to this and find a fix. Pretty slammed right now but should soon have some time for bug fixes.

**Comment by kevinwarne** [comment]
It's a bit late but this should be fixed as of d2b@1.0.0-beta.2

Going through and overhauling this library a bit. Hoping to have better docs / guides and chart configs. So, this fix will get in the official release within the next couple weeks.
