### ISSUE TITLE
How to hide/remove legend ?

### ISSUE THREAD

**Issue by sylfel** [d2bjs/d2b#21]
I'm using a boxplot in a chartAxis with vuejs and i would like to remove legend 
i try
`config: function (axis) {axis.legend(false)}`
but i got error `p.legend.empty`

**Comment by kevinwarne** [comment]
Try this. 
```javascript
config: function (axis) {
  axis.chartFrame().legendEnabled(false)
}
```
http://docs.d2bjs.org/utils/chart_frame.html#legend_enabled

**Comment by sylfel** [comment]
Perfect ! 
Thanks
