### ISSUE TITLE
How to set initial position of nodes in sankey diagram?

### ISSUE THREAD

**Issue by fergardi** [d2bjs/d2b#22]
Hello everyone! Nice library in here.

I'm trying to set the initial position of the nodes in the sankey diagram, but got stuck in using the `.nodes()` method.

What I get is this:

![image](https://user-images.githubusercontent.com/3602272/48697541-25433600-ebe5-11e8-99d2-ccc171c916ad.png)

But I need to be set like this (without manually dragging it):

![image](https://user-images.githubusercontent.com/3602272/48697583-3db35080-ebe5-11e8-9ad3-f841ead1e12c.png)

To give all the info, I'm using [the vuejs wrapper](https://github.com/d2bjs/vue-d2b), but I don't think this issue belongs in there.

This is my code:

```javascript
chartConfig (config) {
        config
          .sankey()
          // .nodes(nodes => console.log(nodes)) // GIVES ERROR
          // .links(links => console.log(links)) // GIVES ERROR
          .nodeDraggableX(false)
          .nodeDraggableY(true)
          .nodeColor((obj, index) => {
            return index >= 4 ? bad : index >= 2 ? neutral : index >= 1 ? good : origin
          })
          .linkSourceColor((obj, index) => {
            return origin
          })
          .linkTargetColor((obj, index) => {
            return index >= 3 ? bad : index >= 1 ? neutral : good
          })
          .sankey()
          // .nodes(nodes => console.log(nodes)) // GIVES ERROR
          // .links(links => console.log(links)) // GIVES ERROR
          .nodePadding(50)
}
```

I'm trying to access the nodes or the links to manually force the first node's initial `.y` coordinate to equal 0 but no luck so far. No matter where I try to access those methods, it always gives me this error:

![image](https://user-images.githubusercontent.com/3602272/48697784-c03c1000-ebe5-11e8-83c4-c0762933c5f0.png)

I don't get what I am doing wrong, cause I was able to use the other methods ` .nodeColor()`, `.linkSourceColor()` and `.linkTargetColor()` with no problem, as stated in [the docs](https://docs.d2bjs.org/svg/sankey.html#nodes).

Any help will be appreciated.

Thank you!

**Comment by kevinwarne** [comment]
This is a tough one. Unfortunately you cannot overwrite the sankey `.nodes` / `.links` properties as they are always coerced during chart rendering.

The best option would be to use d3's built in `sankey.iterations` property to see if another iteration produces the sankey like you are hoping for. Example:
```javascript
chartConfig (config) {
        config
          .sankey()
          .sankey()
          .iterations(0)
}
```

If this doesn't work there is a way to programmatically force the node drag position after rendering and then re-render based on that.

First listen for the rendered event in the template:
```html
  <sankey-chart 
    @rendered = 'chartRendered'
    :config = 'chartConfig'
    :data = 'chartData'
  ></sankey-chart>
```

Next add the chartRendered method to the vue instance:
```javascript
  methods: {
    // This will trigger every time vue re-renders the chart. Might want
    // to unbind this event after the first time to avoid resetting user drags
    chartRendered (el, config) {
      // Select all rendered sankey nodes
      d3.select(el).selectAll('.d2b-sankey-node')
        // Select desired node that you want to force drag position on
        .filter(d => d.data.name === 'Node A')
        // Set drag position as a percent of the chart height
        .each(function (d) { this.__dragY0 = 0.25})
      
      // Progromatically trigger an update to the chart using the chart
      // svg selection and config
      d3.select(el).select('svg').call(config)
    }
  }
```

This makes use of the `__dragY0` value placed on the node DOM elements which is used by d2b to persist drag positions from one update to the next.

Hope this helps, Cheers!
