### ISSUE TITLE
Add example to sort bar chart

### ISSUE THREAD

**Issue by HJK181** [d2bjs/d2b#24]
I'm using a stacked axis chart where I try to apply a fixed sorting to the labels, as the default sorting changes every time I get new data.

I tried to configure the y axis as follows:
```
.y(function (d, points) {
                return {
                  axis: d3.axisLeft().tickFormat(function (t) {
                    return d3.format(",.0%")(t);
                  }),
                  scale: d3.scaleLinear()
                    .domain(points)
                    .range(["unmapped", "remapped", "selfmapped"])
                }
              })
```
without success. Could you add an example for sorting to your documentation? In the closed issues I only found an example how to sort the sunburst chart, but there one can use the .sort method of the d3 pie. I didn't find any sort method on the svgBar generator, so I tried it with the above code.

My data contains percentage values on the y axis and timestamps on the x axis. I guess the scale for the y axis defines the sorting of the percentage values instead of the labels. But how can I sort the stacked labels?

**Comment by HJK181** [comment]
I think I found something on your documentation. I need to configure the Stack object which creates a d3.stack that has a order property: https://github.com/d3/d3-shape#stack

Will update the issue if I have a working solution.

**Comment by HJK181** [comment]
Hm .. I don't know what to do with the created stacker after calling d2b.stack(). I tried calling `.call(stacker)` on the axis chart but this doesn't seam to be correct ...

**Comment by HJK181** [comment]
@kevinwarne any tips for me? Do you still maintain the project?

**Comment by kevinwarne** [comment]
Hi there sorry for missing this issue earlier. You are correct that you can use the stack to order the items. However looking back I didn't expose the stacker for the svgBar generator. I've patched d2b to version `1.0.11` so if you upgrade it should be there. Now on to how to use this..

Let's say you have a bar generator initialized: `const barGen = d2b.svgBar()`

Then you can set the stack order by setting the order property on the "d3 stack" `barGen.stack().order(series => return [/* return the indicies that represent the series order in which they should be stacked */])`.

There are some prebuilt ordering functions that d3 provides. You may reference d3's [stack_order](https://github.com/d3/d3-shape/blob/v1.3.7/README.md#stack_order) or [stack_orders](https://github.com/d3/d3-shape/blob/v1.3.7/README.md#stack-orders) for more info.

Hope this helps!

**Comment by HJK181** [comment]
Hi @kevinwarne 

thx for your detailed reply. However, I'm getting `barGen.stack is not a function` with the following code:
```
const barGen = d2b.svgBar();
              barGen.stack()
                .order(series => {
                  console.log(series);
                  return [];
                });
              barGen.stackBy(d => d.stack);
```

**Comment by kevinwarne** [comment]
Hmm, what version of d2b are you using? Make sure it’s 1.0.11

**Comment by HJK181** [comment]
Package json says 1.0.11, but when I inspect the db2.js in the dist folder I can see a version property which is 1.0.10. Did you maybe forgott to build the Project?

**Comment by HJK181** [comment]
After deleting db2 from my node_modules folder and a subsequent `npm install` the error is gone ...
Strange because I saw version `1.0.11` in the package.json of db2 ...

**Comment by kevinwarne** [comment]
This is possible. I rebuilt and upgraded to 1.0.12 just in case I did forgot to build the production env. Cheers.

**Comment by HJK181** [comment]
Thank you very much.
