### ISSUE TITLE
Import problem

### ISSUE THREAD

**Issue by tantan-thrymr** [d2bjs/d2b#7]
After installing d2b ,how will i import for ??????????

**Comment by 8bit-echo** [comment]
From what I can tell you need to import the module by its export name, or import the library from d2b/build/d2b.js which does not work for me since it also requires d3 as a dependency. Importing d3 separately doesn’t resolve the issue though.

**Comment by kevinwarne** [comment]
Sorry I've been caught up doing other things the past couple months. Just getting back to d2b development now. 

If you are importing via ES6 or node you can simply import d2b. You do not have to separately include d3 as it is a node dependency. Of course if you include d3 elsewhere then feel free to add it as a dependency anyway..

es6:
```javascript
import * as d2b from 'd2b'
```

node:
```javascript
const d2b = require ('d2b')
```
If you are simply including the minified version into a browser you can src in the latest from unpkg, with this method you must also manually include d3 as the dependency:
```javascript
<script src = 'https://unpkg.com/d3@4.11.0/build/d3.min.js' />
<script src = 'https://unpkg.com/d2b@0.0.35/build/d2b.min.js' />
```

Let me know if you continue to have problems importing the library. Thanks!

**Comment by ammarbajwa** [comment]
I'm trying to source in using the minified version using the following link : 

`<script src = "https://unpkg.com/d2b@1.0.12/dist/d2b.min.js" /> `

But I get the following error: 
ReferenceError: d2b is not defined

I am also including d3 v5. So I know thats not a problem.

**Comment by HJK181** [comment]
Hi @kevinwarne 
I'm also having issues with importing d2b as ES-Module. I'm using the following versions (package.json):
```
 "d2b": "^1.0.12",
 "d3": "^5.9.2",
```
I'm than importing d3 and d2b in the following manner:
```
import { select } from 'd3-selection';
import { axisBottom, axisLeft } from 'd3-axis';
import { scaleUtc } from 'd3-scale';
import { format } from 'd3-format';
import { utcDay, utcWeek, timeDay } from 'd3-time';
import { timeFormat } from 'd3-time-format';
import { min, max } from 'd3-array';
import { interpolateRgb } from 'd3-interpolate';
// import { chartAxis, svgBar } from 'd2b';
import * as d2b from 'd2b';
```
which results in 
```
Uncaught ReferenceError: exports is not defined
    at d2b.cjs.js:3
```

**Comment by HJK181** [comment]
If I change it to
```
import { select } from 'd3-selection';
import { axisBottom, axisLeft } from 'd3-axis';
import { scaleUtc } from 'd3-scale';
import { format } from 'd3-format';
import { utcDay, utcWeek, timeDay } from 'd3-time';
import { timeFormat } from 'd3-time-format';
import { min, max } from 'd3-array';
import { interpolateRgb } from 'd3-interpolate';
import { chartAxis, svgBar } from 'd2b';
```
I'm getting:
```
Uncaught SyntaxError: The requested module '../node_modules/d2b/dist/d2b.cjs.js' does not provide an export named 'svgBar'
```

**Comment by HJK181** [comment]
@kevinwarne 
it works if I use
```
import { chartAxis, svgBar } from 'd2b/src/scripts/index.js';
``` 
but only if I uncomment the scss import
```
import '../styles/index.scss';
```
otherwise I get
```
Failed to load module script: The server responded with a non-JavaScript MIME type of "text/x-scss". Strict MIME type checking is enforced for module scripts per HTML spec.
```
